<?php
return array(
	'header_menu_text_color' => '#2b2b2b',
    'header_menu_text_hover_color' => '#ec2327',
    'header_menu_submenu_text_color' => '#444444',
    'header_menu_submenu_text_hover_color' => '#ec2327',
    'header_menu_submenu_border_color' => '#e0e0e0',
    'header_ads_active' => '1',
    'header_social_icons_active' => '1',
    'header_ads_content' => '<a href="#"><img src="'.esc_url('http://via.placeholder.com/600x80').'"></a>',
    'header_style_color_mood' => 'dark',
    'header_style_bg_color' => '#ffffff',
    'footer_widgets_layout' => '3/3/3/3',
    'footer_widgets_layout_t' => '6',
    'footer_widgets_layout_m' => '12',
    'footer_widgets_color_mood' => 'light',
    'footer_widgets_padding_top' => '50px',
    'footer_widgets_active' => '1',
    'footer_bar_style_color_mood' => 'light',
    'footer_bar_style_padding_top' => '20px',
    'footer_bar_style_padding_bottom' => '20px',
    'footer_widgets_padding_bottom' => '0px',
    'footer_widgets_padding_top_t' => '30px',
    'footer_widgets_padding_bottom_t' => '0px',
    'footer_widgets_padding_top_m' => '30px',
    'footer_widgets_padding_bottom_m' => '0px',
    'footer_widgets_bg_color' => '#222631',
    'footer_copy_text' => 'Copyright 2017 All Right Revised.',
    'primary_l_color' => '#ed5053',
    'primary_color' => '#ec2327',
    'primary_d_color' => '#d60039',
    'accent_color' => '#0977b9',
);